# sourced from https://repo1.dso.mil/platform-one/quick-start/big-bang/-/blob/master/start.yaml
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: bigbang

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: environment-repo
  namespace: bigbang
spec:
  interval: 1m
  #url: https://github.com/recarmona/bigbang.git
  url: https://github.com/recarmona/template.git 
  #url: https://repo1.dso.mil/platform-one/big-bang/bigbang.git
  #url: https://repo1.dso.mil/platform-one/quick-start/big-bang.git
  ref:
    branch: template-demo

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: environment
  namespace: bigbang
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: environment-repo
  path: ./dev
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
